### PR TITLE
Add gentx Making.cash

### PR DESCRIPTION
**Pull request by Alive29**

### CODE REVIEW

**Comment by shanev** [comment]
Please make sure your node is up and running. Join #validators Discord for help: https://discord.gg/QeJWCrE.

**Comment by Alive29** [comment]
> Please make sure your node is up and running. Join #validators Discord for help: https://discord.gg/QeJWCrE.

This is a joke? You haven't added my address to genesis. Why should I run a node?

**Comment by jhernandezb** [comment]
Your gentx had wrong signature and had to be removed from genesis, the fact that you just noticed would have prevented us from starting the network, sorry that this was last minute If you already have your node synced we can send tokens to create the validator and participate

**Comment by Alive29** [comment]
> Your gentx had wrong signature and had to be removed from genesis, the fact that you just noticed would have prevented us from starting the network, sorry that this was last minute If you already have your node synced we can send tokens to create the validator and participate

Yes, my node synced. Send please tokens stars13s5jt5a5w86904m7z3z45cvtf0aetf7mwwn2yx

**Comment by jhernandezb** [comment]
sent create your validator following instructions (check the right amount 9000000ustarx)

**Comment by Alive29** [comment]
Thanks!

**Pull request merged**
