### PR TITLE
Rename starsd to staked

### PR DESCRIPTION
**Pull request by the-frey**
Apologies if the find & replace is too aggressive, just noticed it as I was running through.

### CODE REVIEW

**Comment by shanev** [comment]
@the-frey It should be `starsd`. Are you running an older version maybe?

**Comment by JakeHartnell** [comment]
You're running the old version.

**Comment by JakeHartnell** [comment]
You were likely following the `albatross-1` testnet instructions and installed the old binary.

**Comment by JakeHartnell** [comment]
You can find the correct instructions for the bellatrix testnet here: https://github.com/public-awesome/testnets/tree/master/bellatrix-1

Remove the `staked` binary and start over with the new instructions. Thanks for the PR though! We do appreciate those if you come across something that doesn't work.

**Comment by the-frey** [comment]
This is why I shouldn't do stuff late at night. PEBKAC - sorry about that!

**Pull request closed without merging**
