### PR TITLE
[Phase 1][Challenge 1] sr

### PR DESCRIPTION
**Pull request by umitbeniz**

### CODE REVIEW

**Comment by jhernandezb** [comment]
can you change the name of the file?

**Comment by umitbeniz** [comment]
> can you change the name of the file?

Sure. what do you want as

**Comment by jhernandezb** [comment]
must be your moniker (validator name) as seen in the explorer

**Comment by umitbeniz** [comment]
> must be your moniker (validator name) as seen in the explorer

i changed "moniker.json" to "sr.json".
is it ok?

**Comment by umitbeniz** [comment]
> must be your moniker (validator name) as seen in the explorer

I am closing this PR. I will create a challenge-1 branch then send my tx information.

For your information.

**Pull request closed without merging**
